plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.jitsiapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.jitsiapp"
        minSdk 26
        targetSdk 34
        versionCode 1  // Увеличивать каждый раз при обновлении
        versionName "1.1.1"  // Увеличивать каждый раз при обновлении

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    implementation 'org.jitsi.react:jitsi-meet-sdk:8.1.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

android.applicationVariants.all { variant ->
    variant.outputs.all { output ->
        outputFileName = "JitsiVideoChat-v${variant.versionName}.apk"
    }
}