name: Build & Release APK

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.json in jitsi-update
        run: |
          TAG_NAME=${GITHUB_REF_NAME#v}

          cat > version.json <<EOF
          {
            "versionCode": $(echo "$TAG_NAME" | awk -F. '{print $3}'),
            "versionName": "$TAG_NAME",
            "apkUrl": "https://github.com/sSergey8/jitsi-release/releases/download/v$TAG_NAME/JitsiVideoChat-v$TAG_NAME.apk"
          }
          EOF

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone https://x-access-token:${{ secrets.UPDATE_REPO_TOKEN }}@github.com/sSergey8/jitsi-update.git
          cd jitsi-update

          mv ../version.json .
          git add version.json
          git commit -m "Update version to v$TAG_NAME"
          git push
